### ISSUE TITLE
Cannot find this extension in vs code 

### ISSUE THREAD

**Issue by maxnoe** [AREA44/vscode-LaTeX-support#10]
This extension somehow is not available anymore through the extensions marketplace in vs code.

Any idea why?

**Comment by maxnoe** [comment]
![Screenshot_20201019_134139](https://user-images.githubusercontent.com/5488440/96445935-fab6e900-1210-11eb-8003-c49ffddb277a.png)

**Comment by torn4dom4n** [comment]
@maxnoe sorry for the delay. Did you install this extension before? BTW, I want to know your VSCode version.

**Comment by maxnoe** [comment]
Yes, I did install the extension before, although not on that machine.
VS Code is up to date.

I also don't think that really matters, we organized a remote workshop with > 60 participants and noone was able to install the extension.

**Comment by torn4dom4n** [comment]
I can't reproduction your issue:

**Comment by maxnoe** [comment]
I cannot even find it in the market place when entering `ext install torn4dom4n.latex-support` in `Ctrl + P`

It is really strange. I am in Germany by the way, all the workshop participants were as well.

Maybe it's somehow geoblocked???

**Comment by maxnoe** [comment]
```
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-15T10:42:48.064Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.18-1-MANJARO
```

**Comment by bregeon** [comment]
works for me from France just now:
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:44:48.716Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.16-200.fc32.x86_64

**Comment by torn4dom4n** [comment]
First, you can try to download the extension from [the lastest release](https://github.com/AREA44/vscode-LaTeX-support/releases/latest) and install it.
Second, I open an issue on VSCode repo. I don't think the error from my extension.

**Comment by torn4dom4n** [comment]
This is problem https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178. For now, you should install from `vsix` file.

**Comment by maxnoe** [comment]
But that means it is not solved? 

This extension is simply not available for vs codium / arch builds?

I would not have thought that vs coding/ code on arch use a different market place.

**Comment by torn4dom4n** [comment]
@maxnoe As you can see, it doesn't come from my extension. I have observed other related issues on VSCode but most of it was closed and publish on OpenVSX as the solution at the moment https://github.com/taniarascia/new-moon/issues/50. Another, go to [Marketplace](https://marketplace.visualstudio.com/vscode), search extension, download and install a `vsix` file.
I hope Microsoft asked ArchLinux to support https://github.com/microsoft/vscode/issues/109773#issuecomment-720315685.
I couldn't do more.

**Comment by torn4dom4n** [comment]
I published it [here](https://open-vsx.org/extension/torn4dom4n/latex-support) 🔥 🔥 

![image](https://user-images.githubusercontent.com/27698189/110365710-ecf6e880-8077-11eb-9009-0d95f921d450.png)
