### ISSUE TITLE
Publish to OpenVSX marketplace

### ISSUE THREAD

**Issue by MrCustomizer** [AREA44/vscode-LaTeX-support#12]
Would you be willing to add your extension to the OpenVSX marketplace. Further information is available here: https://www.gitpod.io/blog/open-vsx/

**Comment by torn4dom4n** [comment]
For your question, I will publish it as soon as possible.

**Comment by torn4dom4n** [comment]
I published it [here](https://open-vsx.org/extension/torn4dom4n/latex-support) 🔥 🔥 

![image](https://user-images.githubusercontent.com/27698189/110365710-ecf6e880-8077-11eb-9009-0d95f921d450.png)
