### ISSUE TITLE
Line comment does not work in \cite

### ISSUE THREAD

**Issue by tueda** [AREA44/vscode-LaTeX-support#14]
Sometimes I use the `\cite` command with a multi-lined argument with line comments. But the syntax highlighting does not seem to work for line comments in the `\cite` command.

- VSCode Version: 1.57.1
- OS Version: Windows_NT x64 10.0. 19042

Steps to Reproduce:

1. Write any comment lines in the `\cite` command argument.

Expected behavior:

Syntax highlighting should work for comment lines in `\cite`.

Logs:

None. (Sorry, I do not see any logs starting with `Initializing LaTeX language support`. Please clearly document how and where one can find it.)

Screenshots:

![image](https://user-images.githubusercontent.com/1481665/124357123-d98a1180-dc54-11eb-9741-7fa599a62d5d.png)

Disable all the other extensions except for `LaTeX language support`, and check that you still see this issue? Yes.

**Comment by torn4dom4n** [comment]
@tueda Thanks for your feedback. I'll check it.
