### ISSUE TITLE
Do I need to install this extension while LaTeX Workshop installed

### ISSUE THREAD

**Issue by heartacker** [AREA44/vscode-LaTeX-support#17]
hi，there is a question ,

I want to know whether necessary to install this extension while  LaTeX Workshop installed

**Comment by torn4dom4n** [comment]
Hi @heartacker, my extension focus on syntax highlighting and snippets for `LaTeX` language. If someone needs a simple extenison, here is it. You can use it with [texlab](https://marketplace.visualstudio.com/items?itemName=efoerster.texlab) as a good alternative LaTeX Workshop.
Thanks for your questions.
