### ISSUE TITLE
Consume grammar files from vscode-latex-basics instead of LaTeX-Workshop

### ISSUE THREAD

**Issue by jlelong** [AREA44/vscode-LaTeX-support#18]
Hi, I am a PM at LaTeX-Workshop. We have recently decided to outsource of grammar files for BibTeX, LaTeX and TeX to https://github.com/jlelong/vscode-latex-basics as they will be used to provide built-in support in the next VS Code release (January 2022). The grammar files will eventually disappear from LaTeX-Workshop.

Could you change your scripts to get the grammar and language configuration files from https://github.com/jlelong/vscode-latex-basics if you want to support old VS Code versions?

**Comment by torn4dom4n** [comment]
Thanks, I'll do it.
