### ISSUE TITLE
Quicklinks in \input command

### ISSUE THREAD

**Issue by t-buss** [AREA44/vscode-LaTeX-support#2]
The `\input{someFile}` command is used to insert other files from the project directory in the document. It would be nice if you could ctrl-click on the "link" inside the command to open the referenced file in a new tab

**Comment by torn4dom4n** [comment]
Thanks @tbuss33. Now, I am only focusing on `LaTeX` syntax. I need more time to develop it.

**Comment by coxackie** [comment]
My two cents: I think this extension should just focus on grammar. I am right now using it with the [texlab](https://marketplace.visualstudio.com/items?itemName=efoerster.texlab) extension, and together I think they provide a good alternative to using Latex workshop that tries to go too much. I would even go to the length of removing the snippets, and potentially have them as a separate extension, as they may be colliding with some user-defined ones.

**Comment by torn4dom4n** [comment]
That is a good idea. Thank for your suggest. I think I'll close this issue.

> My two cents: I think this extension should just focus on grammar. I am right now using it with the [texlab](https://marketplace.visualstudio.com/items?itemName=efoerster.texlab) extension, and together I think they provide a good alternative to using Latex workshop that tries to go too much. For example, the ctrl-click is supported by texlab - it very nicely implement the LSP.
> 
> I would even go to the length of removing the snippets, and potentially have them as a separate extension, as they may be colliding with some user-defined ones.

That is a good idea. Thank for your suggest. I think I'll close this issue.
