### ISSUE TITLE
#region and #endregion snippets constantly show up

### ISSUE THREAD

**Issue by jerryweixd** [AREA44/vscode-LaTeX-support#20]
- VSCode Version: 1.63.2
- OS Version: Windows 10

Steps to Reproduce:

1. When I type in the middle of a line, #region and #endregion snippet constantly shows up (even if I type random things), and autocompletion that suppose to show up does not show up.
2. The problem does not occur when typing at the end of a line.

Screenshots:

![image](https://user-images.githubusercontent.com/71612635/149650369-17d0a697-b53d-40df-a421-cef589a18b24.png)
This is expected:
![image](https://user-images.githubusercontent.com/71612635/149650385-f0af92ab-e9ab-4bf5-907a-de41d2519359.png)

**Comment by torn4dom4n** [comment]
@jerryweixd I transferred this issue to https://github.com/microsoft/vscode/issues/141260
