### ISSUE TITLE
\left and \right cannot be matched properly

### ISSUE THREAD

**Issue by trisct** [AREA44/vscode-LaTeX-support#9]
In some cases I need to use only one left bracket like this: $\left\{...\right.$. But in syntax highlighting, \left and \right cannot be matched and "\{" will be matched to the next "}". This totally messes up all parenthesis matching that comes after.

**Comment by torn4dom4n** [comment]
Hi @trisct, can you submit a file or an image about your issue?

**Comment by torn4dom4n** [comment]
Fixed in v3.5.0.
